builds:
  - binary: helm-release
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archives:
- id: tar
  format: tar.gz
  files:
    - README.md
    - LICENSE
    - plugin.yaml
    - install-binary.sh
